molmod/routes/blast_routes.py
"""
This module contains routes involved in blast processing and
result display. The blast-worker containers are called from the
/blast_run endpoint in this module.
"""
import json

import requests
from flask import Blueprint
from flask import current_app as APP
from flask import jsonify, render_template, request
from forms import BlastResultForm, BlastSearchForm

from config import get_config
from molmod import custom_login_required

CONFIG = get_config()

blast_bp = Blueprint('blast_bp', __name__,
                     template_folder='templates')


@blast_bp.route('/blast', methods=['GET', 'POST'])
@custom_login_required
def blast():
    """Displays both blast search and result forms. The result table is
       populated on submit via (DataTables) AJAX call to '/blast_run',
       which in turn calls a blast-worker container.
    """

    # Create forms from classes in forms.py
    sform = BlastSearchForm()
    rform = BlastResultForm()

    # Only include result form if BLAST button was clicked
    if request.form.get('blast_for_seq') and sform.validate_on_submit():
        return render_template('blast.html', sform=sform, rform=rform)
    return render_template('blast.html', sform=sform)


@blast_bp.route('/blast_run', methods=['POST'])
@custom_login_required
def blast_run():
    """
    Sends blast run request to one of the available blast workers, and then
    adds subject sequences to the output, via a separate function, and returns
    a JSON Response (or an empty string if error occurs).
    """

    form = dict(request.form.lists())
    form['db'] = CONFIG.BLAST_DB
    response = requests.post('http://blast-worker:5000/', json=form)
    if not response.ok:
        APP.logger.error('Error response returned from worker')
        # If error: Return '' instead of None, to avoid logging Werkzeug stack
        # (visible on next request for some reason).
        # jQuery will display custom error msg
        return ''

    #
    # If there are results, format them and add subject sequence before
    # returning.
    #

    results = response.json()
    results = results['data'] if 'data' in results else results

    # Limit results sent to browser to max 1000 rows
    results = results[0:1000]

    # Format result fields
    for result in results:
        # Set single decimal for Sci not & float
        result['evalue'] = f'{result["evalue"]:.1e}'
        # Set identity and coverage as single decimal floats
        result['pident'] = f'{result["pident"]:.1f}'
        result['qcovhsp'] = f'{result["qcovhsp"]:.1f}'

        # Print taxonomy on new line
        result['stitle'] = result['stitle'].replace(';', '|')
        # Extract asvid from stitle = id + taxonomy
        result['asv_id'] = result['stitle'].split('-')[0]

    # Get Subject sequence via ID, and add to the results
    asv_ids = [f['asv_id'] for f in results]
    sdict = get_sseq_from_api(asv_ids)

    # If no, or incomplete set of, sequences were retrieved,
    # don't show any result rows at all
    if sdict is None:
        APP.logger.error('No sequences were returned from DB')
        return ''
    else:
        for result in results:
            if result['asv_id'] in sdict:
                result['asv_sequence'] = sdict[result['asv_id']]
            else:
                APP.logger.error(f"No seq found for {result['asv_id']}")
                return ''

    return jsonify(data=results)


def get_sseq_from_api(asv_ids: list) -> dict:
    """ Requests Subject sequences from API,
        as these are not available in regular BLAST response"""

    # Send API request
    url = f"{CONFIG.POSTGREST}/rpc/app_seq_from_id"
    payload = json.dumps({'ids': asv_ids})
    headers = {'Content-Type': 'application/json'}
    try:
        response = requests.request("POST", url, headers=headers, data=payload)
        response.raise_for_status()
    except Exception as ex:
        APP.logger.error('API request for subject sequences returned: %s', ex)
        return None
    else:
        sdict = {item['asv_id']: item['asv_sequence']
                 for item in json.loads(response.text)}
        return sdict

molmod/routes/filter_routes.py
"""
This module contains routes involved in filter search and result display.
"""
import json

import requests
from flask import Blueprint
from flask import current_app as APP
from flask import render_template, request
from forms import FilterResultForm, FilterSearchForm

from config import get_config
from molmod import custom_login_required

CONFIG = get_config()

filter_bp = Blueprint('filter_bp', __name__,
                      template_folder='templates')


@filter_bp.route('/filter', methods=['GET', 'POST'])
@custom_login_required
def filter():
    """Displays both filter search and result forms. Search form dropdowns
       are populates via (Select2) AJAX call to '/request_drop_options/';
       result tables on submit via (DataTables) AJAX call to '/filter_run'.
    """

    # Create forms from classes in forms.py
    sform = FilterSearchForm()
    rform = FilterResultForm()

    # Reapply any dropdown selections after FILTER submit
    filters = [f.name for f in sform if f.type == 'SelectMultipleField']
    for f in filters:
        selected = [(x, x) for x in request.form.getlist(f) if x]
        if selected:
            sform[f].choices = selected
            APP.logger.debug(f'Reapplied selections: {f}: {selected}')

    # Only include result form if FILTER button was clicked
    if request.form.get('filter_asvs'):
        return render_template('filter.html', sform=sform, rform=rform)
    return render_template('filter.html', sform=sform)


@filter_bp.route('/request_drop_options/<field>', methods=['POST'])
@custom_login_required
def request_drop_options(field) -> dict:
    """Forwards (Select2) AJAX request for filtered dropdown options
    (see main.js) to API, and returns paginated data in dict with Select2
    -specific format."""

    # Make dict of selected list values while renaming list keys,
    # e.g. 'kingdom[]' to 'kingdom'
    payload = {k.replace('[]', ''): request.form.getlist(k)
               for k, v in request.form.items() if k.replace('[]', '')
               # Exclude non-list form items, as .getlist is not applicable,
               # and current field, to allow multiple selections in list
               # (otherwise, first selection removes all other options)
               not in ['term', 'page', field]}

    # Clean search term from special characters that cause errors
    term = request.form['term']
    term = ''.join(e for e in term if e not in '!()?*')

    # Add name of field to be filtered, and (user-typed search) term
    payload.update({'field': field, 'term': term})
    # Add pagination data.
    limit = 25
    offset = (int(request.form['page']) - 1) * limit
    # Examples (assuming more=TRUE, see below):
    # 1) User opens dropdown -> select2 sends page=1 -> offset = 0 -> get
    # records 1-25 from db
    # 2) User scrolls past limit -> page = 2 -> offset = 25 -> get 26-50
    payload.update({'nlimit': limit, 'noffset': offset})

    #
    # Send API request
    #

    # Data are sent to a stored db procedure (app_drop_options) which,
    # in turn, dynamically filters data from a db view (app_filter_mixs_tax),
    # based on target field, typed input and selections made in
    # other dropdowns (see db/db-api-schema.sql)
    url = f"{CONFIG.POSTGREST}/rpc/app_drop_options"
    payload = json.dumps(payload)
    APP.logger.debug(f'Payload sent to /rpc/app_drop_options: {payload}')
    headers = {'Content-Type': 'application/json'}
    try:
        response = requests.request("POST", url, headers=headers, data=payload)
        response.raise_for_status()
    except Exception as e:
        APP.logger.error(f'API request for select options resulted in: {e}')
    else:
        # Repackage data into custom format for Select2 boxes
        results = json.loads(response.text)[0]['data']['results']
        count = json.loads(response.text)[0]['data']['count']
        if count > limit:
            # Remove extra record used for pagination check
            results = results[:-1]
        # APP.logger.debug(f"Offset: {offset}, Limit: {limit}, Count: {count}")
        # APP.logger.debug(f"More results: {count > limit}")
        return {'results': results,
                # Enable scrolling if there are at least one additional record
                'pagination': {'more': count > limit}}


@filter_bp.route('/filter_run', methods=['POST'])
@custom_login_required
def filter_run() -> dict:
    """Composes API request for filtered ASV occurrences, based on data
       received in (DataTable) AJAX request, and returns dict
       with DataTables-specific format"""

    # Set base URL for API search
    url = f"{CONFIG.POSTGREST}/app_search_mixs_tax"

    #
    # Append row filters based on POST:ed dropdown selections
    #

    filters = [f for f in request.form if f != 'csrf_token']
    selections = {f: ','.join(
        map(str,request.form.getlist(f))) for f in filters}
    query_parts = []
    for filter, value in selections.items():
        query_parts.append(f'{filter}=in.({value})')
    query_parts.append('limit=1000')

    url += '?' + '&'.join(query_parts)
    # APP.logger.debug(f'URL for API request: {url}')

    #
    # Send API request
    #

    try:
        response = requests.get(url)
        response.raise_for_status()
    except (requests.ConnectionError, requests.exceptions.HTTPError) as e:
        APP.logger.error(f'API request for filtered occurences returned: {e}')
    else:
        results = json.loads(response.text)
        # APP.logger.debug(results)
        return {"data": results}

molmod/routes/main_routes.py
import json
import os
from datetime import datetime as dt

import requests
from flask import (
    Blueprint, abort, current_app as APP, render_template,
    request, send_from_directory, session, url_for)
from flask_mail import Message
from forms import DownloadForm, UploadForm
from werkzeug.utils import secure_filename

from config import get_config
from molmod import custom_login_required

CONFIG = get_config()

main_bp = Blueprint('main_bp', __name__,
                    template_folder='templates')


@main_bp.route('/')
@main_bp.route('/index')
def index():
    return render_template('index.html')


@main_bp.route('/about')
def about():
    # abort(301)
    stats = get_stats()
    return render_template('about.html', rows=stats)


def get_stats() -> dict:
    """Makes API request for db stats, and returns dict."""

    url = f"{CONFIG.POSTGREST}/app_about_stats"

    try:
        response = requests.get(url)
        response.raise_for_status()
    except (requests.ConnectionError, requests.exceptions.HTTPError) as e:
        APP.logger.error(f'API request for db stats returned: {e}')
    else:
        results = json.loads(response.text)
        # APP.logger.debug(results)
        return results


@main_bp.route('/upload', methods=['GET', 'POST'])
# Redirect user to Bioatlas CAS login
@custom_login_required
def upload():
    """Checks whether logged-in user has required role (UPLOAD_ROLE) for file
       upload. Authorized users are sent to upload page; unauthorized users to
       custom 403 Forbidden page. Selected files currently need to pass
       validation in both forms.py and js, the latter of which was added to be
       able to reject larger files faster, and to avoid getting 413 response
       directly from nginx.
    """

    # Get CAS user roles from session
    cas_attributes = session.get('CAS_ATTRIBUTES', None)

    # login_required should mean we're authenticated, but check this
    if not cas_attributes:
        abort(403)

    roles = cas_attributes['cas:authority'].split(',')

    APP.logger.debug(
        f'User has CAS roles: {roles} ')

    # Stop unauthorized users
    if CONFIG.UPLOAD_ROLE not in roles:
        abort(403)

    form = UploadForm()

    if request.method != 'POST':
        return render_template('upload.html', form=form, upload_error=False)

    # User has tried to submit file (POST)
    # Check if it passes (simple) validation in forms.py
    if not form.validate_on_submit():
        return render_template('upload.html', form=form)

    # Get filename
    f = form.file.data
    filename = secure_filename(f.filename)
    # Add user email & time
    email = cas_attributes['cas:email']
    upload_time = dt.now().strftime("%y%m%d-%H%M%S")
    ext_filename = email + '_' + upload_time + '_' + filename

    dir = '/app/data-volumes/uploads'
    if not os.path.exists(dir):
        os.makedirs(dir)
    try:
        f.save(os.path.join(dir, ext_filename))
    except Exception as ex:
        APP.logger.error(f'File {ext_filename} could not be saved due to {ex}')
    else:
        APP.logger.info(f'Successfully uploaded file {ext_filename}')

        # Notify admin
        msg = Message('New file upload',
                      sender=APP.mail.username,
                      recipients=CONFIG.UPLOAD_EMAIL)
        msg.body = f"""
        Hello SBDI-MOL colleagues,

        A new file has been uploaded to the ASV portal:

        Provider email: {email}
        Upload time: {upload_time}
        Original filename: {filename}
        Saved as: {ext_filename}

        Have a nice day!

        / Swedish ASV portal
        """
        try:
            APP.mail.send(msg)
        except Exception as ex:
            APP.logger.error(f"Could not send upload notification due to {ex}")
        else:
            APP.logger.info('Successfully sent upload notification.')
            # Display 'success page' only if upload AND notification worked
            return render_template('uploaded.html', filename=filename)

    # Display error msg if EITHER upload OR email failed, so that data
    # providers get a chance to tell us about uploaded files
    return render_template('upload.html', form=form, upload_error=True)


@main_bp.route('/submit')
def submit():
    # abort(301)
    return render_template('submit.html')


@main_bp.route("/files/<filename>")
def files(filename):
    """Downloads a file without requiring log-in"""

    dir = os.path.join('.', 'static', 'downloads')
    try:
        return send_from_directory(dir, filename, as_attachment=True)
    except FileNotFoundError:
        abort(404)


@main_bp.route("/datasets/<filename>", methods=['GET'])
@custom_login_required
def datasets(filename):
    """Downloads a (log-in protected) dataset file"""
    APP.logger.info(f"Requested download of {filename}")
    dir = '/app/data-volumes/exports'
    try:
        return send_from_directory(dir, filename, as_attachment=True)
    except Exception as e:
        APP.logger.error(f"Failed download of {filename} due to {e}")
        abort(404)


@main_bp.route("/download", methods=['GET'])
@custom_login_required
def download():
    """Lists available datasets"""
    ds = list_datasets()

    # Create forms from classes in forms.py
    dlform = DownloadForm()

    return render_template('download.html', dlform=dlform, rows=ds)


@main_bp.route('/list_datasets', methods=['GET'])
@custom_login_required
def list_datasets() -> dict:
    """Composes API request for available datasets, based on data
       received in (DataTable) AJAX request, and returns dict
       with DataTable-specific format"""

    url = f"{CONFIG.POSTGREST}/app_dataset_list"

    try:
        response = requests.get(url)
        response.raise_for_status()
    except (requests.ConnectionError, requests.exceptions.HTTPError) as e:
        APP.logger.error(f'API request for dataset list returned: {e}')
    else:
        results = json.loads(response.text)  # -> list of dicts
        for ds in results:
            # Only add IPT link if ID was provided
            if ds['ipt_resource_id']:
                ds['ipt_link'] = (CONFIG.IPT_BASE_URL + '/resource?r='
                                  + ds['ipt_resource_id'])
            else:
                msg = f'Dataset {ds["dataset_id"]} has no IPT resource ID'
                APP.logger.warning(msg)
            # Only add Download link if zip exists
            zip_path = os.path.join('/app/data-volumes/exports',
                                    f'{ds["dataset_id"]}.zip')

            if os.path.isfile(zip_path):
                ds['zip_link'] = url_for('main_bp.datasets',
                                         filename=f"{ds['dataset_id']}.zip",
                                         _external=True)
            else:
                APP.logger.warning(f'Zip file does not exist: {zip_path}')

        # APP.logger.debug(results)
        return results

molmod/templates/about.html
{% extends "layout.html" %}

{% block title %}
About
{% endblock title %}

{% block body %}
<div class='container'>
    <div class="col-md-12">
        <h1>About the Swedish ASV portal</h1>
        <p>
            The portal of Swedish Amplicon Sequence Variants (ASVs)
            is an interface to sequence-based observations in
            the <a href="{{ sbdi_start_page }}">
            Swedish Biodiversity Data Infrastructure (SBDI)</a>.
            In addition to a database of amplicon sequence variants (ASVs) and a web interface,
            we provide a
            <a href="{{ ena_guide_page }}"
               rel="noreferrer noopener" target="_blank">step-by-step guide<span class='screen-reader-text'>(Link opens in a new tab)</span></a>
            to submitting raw sequence data to ENA,
            and a
            <a href="{{ ampliseq_page }}" target="_blank" rel="noreferrer noopener">pipeline<span class='screen-reader-text'>(Link opens in a new tab)</span></a> (developed in the nf-core collaboration)
            for denoising and taxonomic annotation of metabarcoding data.
        </p>
        <p>
            <figure>
                <img src="{{url_for('static', filename='img/metabarcoding-sbdi.png')}}"
                     class="img-fluid" title="Flow of metabarcoding data in SBDI" />
                <figcaption><br><b>Flow of metabarcoding data in SBDI</b>: A sequencing service provider, such as NGI, delivers sequencing data
                    to the user. The user submits raw sequencing data and contextual data to ENA
                    (see <a href="{{ ena_guide_page }}"
                    rel="noreferrer noopener">our guide<span class='screen-reader-text'>(Link opens in a new tab)</span></a>), denoises the data using e.g.
                    <a href="{{ ampliseq_page }}" rel="noreferrer noopener" target="_blank">nf-core/ampliseq
                        <span class='screen-reader-text'>(Link opens in a new tab)</span>
                    </a>, and submits the denoised data (ASVs and their counts in different samples, and contextual data)
                    to the ASV portal. Metabarcoding data in the ASV database/Bioatlas
                    can be searched and downloaded in a condensed format using the portal,
                    and downloaded archives can then be unpacked, merged and processed into ASV table format using the
                    <a href="https://github.com/biodiversitydata-se/asvoccur"
                    rel="noreferrer noopener" target="_blank">asvoccur</a> R package.
               </figcaption>
            </figure>
        <p>
            <h2>Why publish data in SBDI?</h2>
            <p>By publishing your data in the Swedish ASV database and Bioatlas
            your data will be easily reusable by others and can be seamlessly analysed
            in conjunction with other datasets in the Bioatlas. The ASVs will be
            regularly re-annoted as new reference database versions are released;
            thus your data will be updated with the latest taxonomic information.
            The ASV database also provides a complement to sequence repositories
            such as ENA or NCBI that typically only store raw sequencing data.
            Data in the Bioatlas is further regularly integrated in GBIF and therefor
            your metabarcoding-based biodiversity data will contribute to global
            knowledge about biodiversity.</p>
        </p>
        <p>
            <h2>Available data</h2>
            <p>Currently, we support inclusion of ASVs from the 16S rRNA gene for prokaryotes,
            the 18S gene for eukaryotes, the internal transcribed spacer (ITS) for fungi,
            and the COI cytochrome c oxidase I (COI) for metazoans. Other markers can be included on request.
            Read more about ASV taxonomy in SBDI
            <a href="{{ taxonomy_page }}">here</a>.</p>
        </p>
        <p>
            <caption><b>Marker genes and taxa currently represented in the ASV database</b></caption>

            <br>
            <table id='stats_table' class='table table-striped'>
                <thead>
                    <tr>
                        <th>Marker</th>
                        <th>Domains/Kingdoms/Supergroups<sup>*</sup></th>
                        <th># Datasets</th>
                        <th># Phyla</th>
                        <th># Classes</th>
                        <th># Orders</th>
                        <th># Families</th>
                        <th># Genera</th>
                        <th># Species</th>
                        <th># ASV:s</th>
                    </tr>
                </thead>

                    {% if rows %}
                    {% for row in rows %}

                    <tr>
                        <td>{{ row.gene }}</td>
                        <td id="top_ranks">{{ row.kingdoms }}</td>
                        <td>{{ row.datasets }}</td>
                        <td>{{ row.phyla }}</td>
                        <td>{{ row.classes }}</td>
                        <td>{{ row.orders }}</td>
                        <td>{{ row.families }}</td>
                        <td>{{ row.genera }}</td>
                        <td>{{ row.species }}</td>
                        <td>{{ row.asvs }}</td>
                    </tr>
                    {% endfor %}
                    {% endif %}
            </table>
        </p>
        {% include ['tax_explainer.html'] ignore missing %}
        <p>
            We are currently working on improving the accessibility of this website.
            <a href="{{ sbdi_contact_page }}">Please contact SBDI support</a> with any questions or suggestions!
        </p>

</div>
{% endblock body %}

molmod/templates/banner.html
<header>

    <!-- Banner-->
    <div class="container">
        <div class="banner">
            <a href="https://biodiversitydata.se/" title="Swedish Biodiversity Data Infrastructure">
                <img src="https://bioatlas.biodiversitydata.se/app/themes/sbdi/assets/images/SBDI-rgb.svg" alt="Swedish Biodiversity Data Infrastructure">
            </a>
            <p>Swedish Biodiversity Data Infrastructure</p>
            <div>
                <a class="hidden-xs" href="https://biodiversitydata.se/explore-data/">
                    <i class="fas fa-arrow-circle-right"></i>&nbsp;All SBDI tools
                </a>
                <br>
                <a class="hidden-xs" href="https://docs.biodiversitydata.se/support/">
                    <i class="fas fa-arrow-circle-right"></i>&nbsp;Support form
                </a>
            </div>
        </div>
    </div>

    <!-- Navbar -->
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar-collapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="nav"><a class="nav" href="{{ url_for('main_bp.index') }}">Swedish ASV portal</a></li>
                    <li class="nav"><a class="nav" href="{{ url_for('blast_bp.blast') }}">BLAST search</a></li>
                    <li class="nav"><a class="nav" href="{{ url_for('filter_bp.filter') }}">Filter search</a></li>
                    <li class="nav"><a class="nav" href="{{ url_for('main_bp.submit') }}">Submit data</a></li>
                    <li class="nav"><a class="nav" href="{{ url_for('main_bp.download') }}">Download data</a></li>
                    <li class="nav"><a class="nav" href="{{ url_for('main_bp.about') }}">About</a></li>
                    <li class="nav visible-xs-inline">
                        <a class="nav" href="https://biodiversitydata.se/explore-data/">All SBDI tools</a>
                    </li>
                    <li class="nav visible-xs-inline">
                        <a class="nav" href="https://docs.biodiversitydata.se/support/">Support form</a>
                    </li>
                    {% if firstname %}
                        <li class="nav"><a class="nav" href="/logout">Log out {{firstname}}</a></li>
                    {% else %}
                        <li class="nav"><a class="nav" href="/login">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

molmod/templates/error_403.html
{% extends 'layout.html' %}

{% block title %}
Permission required
{% endblock title %}

{% block body %}
<div class='container'>
    <div>
        <br>
        <h3>Almost there...</h3>
        <br>
        <p>If this is your first data submission, please request upload permission for your SBDI account.
           Just go to the <a href="{{ sbdi_contact_page }}">SBDI support</a> page,
           select Type = 'ASV portal support', add a sentence about yourself and your data to the Message box,
           and we will get back to you as soon as we can. Thanks for your patience!
        </p>
    </div>
</div>
<br>
<br>


{% endblock body %}

molmod/templates/error_404.html
{% extends "layout.html" %}

{% block title %}
Page not found
{% endblock title %}

{% block body %}
<div class='container'>
    <div>
        <br>
        <h2>Page Not Found</h2>
        <p>{{description}}</p>
        <p><a href="{{ url_for('main_bp.index') }}">Go to Start page</a>
    </div>
</div>
{% endblock body %}

molmod/templates/error_413.html
{% extends "layout.html" %}

{% block title %}
File too large
{% endblock title %}

{% block body %}
<div class='container'>
    <div>
        <br>
        <h3>File Too Large</h3>
        <br>
        <p>The file you tried to upload was larger than the {{ "{:.0f}".format(max_file_size/(1024*1024)) }}
           MB we can deal with here.
       </p>
       <p>
           Please contact <a href="{{ sbdi_contact_page }}">SBDI support</a>,
           and we will find another option for you.
        </p>

    </div>
</div>
{% endblock body %}

molmod/templates/error_generic.html
{% extends "layout.html" %}

{% block title %}
Error
{% endblock title %}

{% block body %}
<div class='container'>
    <div>
        <br>
        <h2>{{name}}</h2>
        <p>{{description}}</p>
        {% if not drop_start %}
            <p><a href="{{ url_for('main_bp.index') }}">Go to Start page</a></p>
        {% endif %}
        {% if not drop_contact %}
            <p><a href="{{ sbdi_contact_page }}">Contact SBDI support</a></p>
        {% endif %}
    </div>
</div>
{% endblock body %}

molmod/templates/index.html
{% extends "layout.html" %}

{% block title %}
Start
{% endblock title %}

{% block body %}
<div class="jumbotron welcome">
    <div class="container">
        <div class="col-md-8">
            <h1>Swedish ASV portal</h1>
            <h3 class="subject-subtitle">
                Explore and share DNA sequences and species occurrences derived from metabarcoding (eDNA) studies</h3>
        </div>
        <div class="col-md-4">
            <img src="{{ url_for('static', filename='img/dna.png') }}"
                 title="ASV portal logo (DNA double helix)" height="200" width="200"
                 class="center-block">
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p>
                Search for ASVs and Bioatlas records using Basic Local Alignment Search Tool (BLAST)<br><br>
                <a class="btn btn-primary" id=blast_link href="{{ url_for('blast_bp.blast') }}" role="button">BLAST</a>
            </p>
        </div>
        <div class="col-md-3">
            <p>
                Search for ASVs and Bioatlas records using filters on sequencing details and taxonomy<br><br>
                <a class="btn btn-primary"  id=filter_link href="{{ url_for('filter_bp.filter') }}" role="button">Filter</a>
            </p>
        </div>
        <div class="col-md-3">
            <p>
                Submit your metabarcoding dataset to the ASV database and SBDI Bioatlas<br><br>
                <a class="btn btn-primary"  id=submit_link href="{{ url_for('main_bp.submit') }}" role="button">Submit</a>
            </p>
        </div>
        <div class="col-md-3">
            <p>
                Download ASV occurrence datasets, in a condensed Darwin Core-like format<br><br>
                <a class="btn btn-primary"  id=download_link href="{{ url_for('main_bp.download') }}" role="button">Download</a>
            </p>
        </div>
    </div>
</div>
{% endblock body %}

molmod/templates/matomo.html
<script type="text/javascript">
    var _paq = window._paq = window._paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
    _paq.push(["setCookieDomain", "*.biodiversitydata.se"]);
    _paq.push(["setDomains", ["*.biodiversitydata.se"]]);
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
        var u="//matomo.biodiversitydata.se/";
        _paq.push(['setTrackerUrl', u+'matomo.php']);
        _paq.push(['setSiteId', '15']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
    })();
</script>
<noscript><p><img referrerpolicy="no-referrer-when-downgrade" src="//matomo.biodiversitydata.se/matomo.php?idsite=15&amp;rec=1" style="border:0;" alt="" /></p></noscript>

molmod/templates/sbdi_post.html
<!-- Hidden part, for redirection to SBDI -->
<div class='row'>
    <textarea name='queries' id='raw_names' style='display: none'></textarea>
    <!-- Make visible for testing: -->
    <!-- <textarea name='queries' id='raw_names' rows=4, cols=40></textarea> -->
    <input type='hidden' name='redirectBase' value={{ rform.redirect_url }} >
    <input type='hidden' name='field' value='taxon_id'/>
    <input type='hidden' name='action' value='Search'/>
</div>
<div class='row'>
    <div class='col-md-12 visHlpDiv hiddenElem' id='dtbl_err_container'>Dummy</div>
</div>
<div class='row'>
    <div class='col-md-3'>
        <input id='show_occurrences' name='show_occurrences' type='submit' value='Show Bioatlas records' class='btn btn-primary'/>
    </div>
</div>
<script>
    var batchUrl = '{{ rform.batch_url }}';
</script>

molmod/templates/tax_explainer.html
<!-- This file is shared between filter search and about page -->
<p>
    <sup>* </sup>To accommodate data from different reference databases,
    and to facilitate data transfer to the Bioatlas and GBIF platforms,
    we group GTDB domains and PR2 supergroups together with
    UNITE and BOLD BIN kingdoms here.
    <a href="{{ taxonomy_page }}">Read more about ASV taxonomy in SBDI</a>.
</p>